name: 'Install Nix'
description: 'Installs Nix on GitHub Actions for the supported platforms: Linux and macOS.'
author: 'Domen Kožar'
branding:
  color: 'blue'
  icon: 'sun'
runs:
  using: 'node12'
  main: 'lib/main.js'
