name: 'Install Nix'
description: 'Installs Nix on GitHub Actions for the supported platforms: Linux and macOS.'
author: 'Domen Kožar'
inputs:
  install_url:
    description: 'Installation URL that will contain a script to install Nix'
  nix_path:
    description: 'Set NIX_PATH environment variable. If set "skip_adding_nixpkgs_channel" will be implicitly enabled'
  skip_adding_nixpkgs_channel:
    description: 'Skip adding nixpkgs-unstable channel'
  extra_nix_config:
    description: 'gets appended to `/etc/nix/nix.conf` if passed.'
branding:
  color: 'blue'
  icon: 'sun'
runs:
  using: 'node12'
  main: 'lib/main.js'
