name: 'Install Nix'
description: 'Installs Nix on GitHub Actions for the supported platforms: Linux and macOS.'
author: 'Domen Kožar'
inputs:
  install_url:
    description: 'Installation URL that will contain a script to install Nix'
  skip_adding_nixpkgs_channel:
    description: 'Skip adding nixpkgs-unstable channel'
branding:
  color: 'blue'
  icon: 'sun'
runs:
  using: 'node12'
  main: 'lib/main.js'
